# Generated by Django 4.1.4 on 2022-12-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emal',
            new_name='email',
        ),
    ]
